name: dev
on:
  pull_request:
  push:
    branches: [dev]
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3

      - name: Test
        run: make test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        run: make image
